version: "3"
services:
  peerstats:
    hostname: peerstats
    build:
      context: ./peerstats
    container_name: peerstats
    ports:
      - 3000:3000
    environment:
      - WS_SECRET=peerpass
      - PORT=3000
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    restart: always
    networks:
      chainnet:
        ipv4_address: 172.25.0.104

  peerboot:
    hostname: peerboot
    environment:
      - nodekeyhex=53cff0434e7c1c0f946848db7bcf56d7fe700b524ebd3b134e047487d44690fb
      - bootnodeIp=172.25.0.105
    build:
      context: ./peerboot
    container_name: peerboot
    ports:
      - 30301:30301
      - 30301:30301/udp
      
    networks:
      chainnet:
        ipv4_address: 172.25.0.105

  peernode-auth-1:
    hostname: peernode-auth-1
    depends_on:
      - peerboot
    environment:
      - address=0x1bb7a110f310934efecfbd88db409a73282c1cc1
      - bootnodeId=e9cc1bfef384ee56563dcbe1c31be69e2ef918932cd0957a6d85fc7040cb2f33e1c6160489f539256262a4c50e05522579eaaa7023d3315983cd2f8d88de19da
      - bootnodeIp=172.25.0.105

      - peerstataddress=172.25.0.104
      - peerstatport=3000       
    build:
      context: ./peersigner
      dockerfile: Dockerfile-node1
      args:
        binary: 1.8.17+build15807+xenial
        signer.pass: peerpass
    container_name: peernine-signer-1
    ports:
      - 8545:8545
      - 30303:30303
      - 30303:30303/udp

    volumes:
      - peer-data-1:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.106

  peernode-auth-2:
    hostname: peernode-auth-2
    depends_on:
      - peernode-auth-1
    environment:
      - address=0x599f16e36dc11736a6827b1458e18e1f325181da
      - bootnodeId=e9cc1bfef384ee56563dcbe1c31be69e2ef918932cd0957a6d85fc7040cb2f33e1c6160489f539256262a4c50e05522579eaaa7023d3315983cd2f8d88de19da
      - bootnodeIp=172.25.0.105

      - peerstataddress=172.25.0.104
      - peerstatport=3000  
    build:
      context: ./peersigner
      dockerfile: Dockerfile-node2
      args:
        password: peerpass
    container_name: peernine-signer-2
    ports:
      - 8546:8545
      - 30304:30304
      - 30304:30304/udp

    volumes:
     - peer-data-2:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.107

  peernode-auth-3:
     hostname: peernode-auth-3
     depends_on:
       - peernode-auth-2
     environment:
       - address=0x5054db3275fde21e93b5d99f81f4d4a215366730
       - bootnodeId=e9cc1bfef384ee56563dcbe1c31be69e2ef918932cd0957a6d85fc7040cb2f33e1c6160489f539256262a4c50e05522579eaaa7023d3315983cd2f8d88de19da
       - bootnodeIp=172.25.0.105

       - peerstataddress=172.25.0.104
       - peerstatport=3000  
     build:
       context: ./peersigner
       dockerfile: Dockerfile-node3
       args:
         password: peerpass
     container_name: peernine-signer-3
     ports:
       - 8547:8545
       - 30305:30305
       - 30305:30305/udp

     volumes:
      - peer-data-3:/root/.ethash
     networks:
       chainnet:
         ipv4_address: 172.25.0.108

networks:
  chainnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
volumes:
  peer-data-1:
  peer-data-2:
  peer-data-3:
