#signer-505
FROM ubuntu:xenial

RUN apt-get update \
     && apt-get install -y wget software-properties-common \
     && rm -rf /var/lib/apt/lists/*

RUN add-apt-repository -y ppa:ethereum/ethereum

#55five
ARG binary
RUN apt-get update \
     && apt-get install -y ethereum=$binary

#55five
ARG signer.pass

RUN echo $signer.pass > /signer.pass

ADD genesis.json /genesis.json
ADD signer-505.json /signer.json
ADD signer.pass /signer.pass

#<-- 55five 여기부턴 init -->
RUN geth --cache 512 init genesis.json
RUN echo mkdir -p /root/.ethereum/keystore/
RUN cp /signer.json /root/.ethereum/keystore/

#환경변수 설정
ENV address=""
ENV bootnodeId=""
ENV bootnodeIp=""

ENV peerstataddress=""
ENV peerstatport=""
ENV peerstatsName=""

#여기서 실행
#CMD exec geth --networkid 13525 --verbosity=4 --rpc --rpcapi "eth,web3,personal,net,miner,admin,debug,db" --rpcaddr "0.0.0.0" --rpccorsdomain "*" --syncmode=full --cache 512 --port 30305 --nat extip:0.0.0.0 --maxpeers 50 --bootnodes "enode://$bootnodeId@$bootnodeIp:30301" --ethstats "peernine-signer-3:peerpass@$peerstataddress:$peerstatport" --etherbase $address --unlock $address --password /signer.pass --gasprice "0" --mine
#soft 4
#CMD exec geth --networkid 13525 --nodiscover --rpc --rpcapi "eth,web3,personal,net,miner,admin,debug,db" --rpcaddr "localhost" --rpccorsdomain "*" --nat extip:0.0.0.0 --bootnodes "enode://$bootnodeId@$bootnodeIp:30301" --ethstats "$peerstatsName:peerpass@$peerstataddress:$peerstatport" --etherbase $address --unlock $address --password /signer.pass --gasprice "0" --mine

CMD exec geth --networkid 13525 --nodiscover --verbosity 6 --rpc --rpcapi "eth,web3,personal,net,miner,admin,debug,db" --rpcaddr "0.0.0.0" --rpccorsdomain "*" --syncmode=full --cache 512 --port 30305 --nat extip:0.0.0.0 --maxpeers 50 --bootnodes "enode://$bootnodeId@$bootnodeIp:30301" --etherbase $address --unlock $address --password /signer.pass --gasprice "0" --mine

EXPOSE 8545
EXPOSE 30305
EXPOSE 30305/udp
