#signer-505
FROM ubuntu:xenial

RUN apt-get update \
     && apt-get install -y wget software-properties-common \
     && rm -rf /var/lib/apt/lists/*

RUN add-apt-repository -y ppa:ethereum/ethereum

#55five
ARG binary
RUN apt-get update \
     && apt-get install -y ethereum=$binary

#55five
ARG signer.pass

RUN echo $signer.pass > /signer.pass

ADD genesis.json /genesis.json
ADD signer-505.json /signer.json
ADD signer.pass /signer.pass

#<-- 55five 여기부턴 init -->
RUN geth --cache 512 init genesis.json
RUN echo mkdir -p /root/.ethereum/keystore/
RUN cp /signer.json /root/.ethereum/keystore/

#환경변수 설정
#ENV address="0x5054db3275fde21e93b5d99f81f4d4a215366730"
ENV address=""
#ENV bootnodeId="a163d57127487a3d3403d6f655b2f36162f0da7bfb92627a26f3634dc9e349d9da05cec8bb04f69b89fd62f4f981b2d305cc5c84f68959397ad9b49a594827f0"
ENV bootnodeId=""
#ENV bootnodeIp="172.25.0.105"
ENV bootnodeIp=""

#여기서 실행
CMD exec geth --networkid 13525 --verbosity=4 --rpc --rpcapi "eth,web3,personal,net,miner,admin,debug,db" --rpcaddr "0.0.0.0" --rpccorsdomain "*" --syncmode=full --cache 512 --port 30301 --nat extip:0.0.0.0 --maxpeers 50 --bootnodes "enode://$bootnodeId@$bootnodeIp:30301" --ethstats='peernine-signer-3:peerpass@172.25.0.104:3000' --etherbase $address --unlock $address --password /signer.pass --gasprice "0" --mine

EXPOSE 8545
EXPOSE 30303
